function r = rsym(CR,delta,psm,rho,robc,theta)
%RSYM
%    R = RSYM(CR,DELTA,PSM,RHO,ROBC,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    23-Dec-2021 13:35:15

t2 = delta.*2.0;
t3 = cos(t2);
r = (psm.*rho.*(cos(t2-theta.*2.0)-t3.*(CR.*2.0-1.0))+CR.*robc.*(rho.*t3+1.0))./(rho.*cos(delta-theta)+1.0);
